name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
     
  build: 
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v3
      with:
        ref: refs/pull/${{ github.event.number }}/head
    - name: Auto-Format with pretty-quick
      env: 
        git_branch_ref:  refs/pull/${{ github.event.number }}/head
      run: npx -p prettier@3.0.2 -p pretty-quick@3.1.3 pretty-quick --staged --branch git_branch_ref
    - name: Commit auto-formatted files
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      uses: stefanzweifel/git-auto-commit-action@v4
      if: ${{ github.event_name == 'pull_request'}}
      with:
          commit_message: "style: format files"
#Experimental Auto-format ends here

    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
